// Generated by `pnpm db:types` once migrations land (T05+). Placeholder keeps
// the server/browser clients typed against *something* in the meantime.
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
